# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 14:07
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoWidget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=32)),
                ('text', models.TextField(default='', max_length=256)),
            ],
            options={
                'db_table': 'infowidgets',
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='UB ACM Newsletter', max_length=40)),
                ('header_image', models.ImageField(blank=True, help_text='This appears at the top of the email, leave blank for default.', null=True, upload_to='newsletters/images')),
                ('text', models.TextField(blank=True, default='', help_text='Leave this blank if using an HTML file.')),
                ('sent_on', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'newsletters',
                'ordering': ['-sent_on'],
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='infowidget',
            name='newsletter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='contacts.Newsletter'),
        ),
    ]
