# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_remove_newsletter_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infowidget',
            options={'verbose_name': 'Newsletter Section', 'verbose_name_plural': 'Text Widgets'},
        ),
        migrations.AddField(
            model_name='newsletter',
            name='intro',
            field=models.TextField(blank=True, default='', help_text='If you want, a little paragraph about how things are going.'),
        ),
    ]
