# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_profile_send_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='header_image',
        ),
    ]
