# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-29 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_ideamachine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infowidget',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
