# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-31 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_auto_20160829_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='send_out',
            field=models.BooleanField(default=False, help_text='SET THIS TO FALSE THE FIRST TIME YOU SAVE!'),
        ),
    ]
