# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-31 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_newsletter_send_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='send_out',
        ),
    ]
