# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 01:00
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
                ('location', models.CharField(default='', max_length=64)),
                ('description', models.TextField(default='', help_text='Please include a contact email/phone', max_length=256)),
                ('time', models.CharField(default='', max_length=10)),
                ('date', models.DateField(default=datetime.date.today)),
                ('attendees', models.ManyToManyField(related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'events',
                'ordering': ['-date'],
            },
        ),
    ]
