# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20160408_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='link',
            field=models.CharField(blank=True, default='', help_text='This can be blank.', max_length=128),
        ),
    ]
