# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='picture',
            field=models.ImageField(blank=True, help_text='Optional, but can be used.', null=True, upload_to='events/images/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='link',
            field=models.CharField(blank=True, default='', help_text='This can be blank. If not, needs http:// and all', max_length=128),
        ),
    ]
