# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 17:13
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0004_auto_20160409_0253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('overview', models.TextField(default='')),
                ('extra_question', models.CharField(default='What is your favorite movie?', max_length=120)),
                ('is_open', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'meetings',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_question_answer', models.TextField(default='')),
                ('comments', models.TextField(blank=True, default='', null=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='events.Meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'responses',
            },
        ),
        migrations.RemoveField(
            model_name='event',
            name='attendees',
        ),
    ]
