# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Not needed, but give brief overview', max_length=128),
        ),
    ]
