# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 05:42
from __future__ import unicode_literals

from django.db import migrations, models
import lib


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='identity',
            field=models.CharField(default=lib.random_generator, max_length=16),
        ),
    ]
