# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 16:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_html_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='html_file',
        ),
    ]
