# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_post_html_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='markdown_file',
        ),
        migrations.AddField(
            model_name='post',
            name='html_file',
            field=models.FileField(blank=True, null=True, upload_to='blog/html/'),
        ),
    ]
