# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20160413_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='html',
            field=models.TextField(default=''),
        ),
    ]
