# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_html'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='html_file',
        ),
        migrations.AddField(
            model_name='post',
            name='template',
            field=models.CharField(default='', max_length=120),
        ),
    ]
