# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20160503_1951'),
        ('blog', '0012_auto_20160505_1421'),
    ]

    operations = [
    ]
