# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 02:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0012_auto_20160505_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=70)),
                ('description', models.TextField(blank=True, default='', help_text='Not needed, but give brief overview', max_length=128)),
                ('markdown', models.TextField(default='')),
                ('is_approved', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prequests',
            },
        ),
    ]
