# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 14:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=65)),
                ('email', models.CharField(default='', max_length=76)),
                ('phone', models.CharField(default='', max_length=13)),
                ('message', models.TextField(default='')),
                ('sent_at', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'contactforms',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='EBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default='2016-2017', max_length=9)),
                ('president_name', models.CharField(default='', max_length=32)),
                ('president_grade', models.CharField(default='', max_length=32)),
                ('president_major', models.CharField(default='', max_length=32)),
                ('president_site', models.CharField(default='', max_length=64)),
                ('president_picture', models.ImageField(upload_to='eboard/profiles/')),
                ('vp_name', models.CharField(default='', max_length=32)),
                ('vp_grade', models.CharField(default='', max_length=32)),
                ('vp_major', models.CharField(default='', max_length=32)),
                ('vp_site', models.CharField(default='', max_length=64)),
                ('vp_picture', models.ImageField(upload_to='eboard/profiles/')),
                ('tresurer_name', models.CharField(default='', max_length=32)),
                ('tresurer_grade', models.CharField(default='', max_length=32)),
                ('tresurer_major', models.CharField(default='', max_length=32)),
                ('tresurer_site', models.CharField(default='', max_length=64)),
                ('tresurer_picture', models.ImageField(upload_to='eboard/profiles/')),
                ('secretary_name', models.CharField(default='', max_length=32)),
                ('secretary_grade', models.CharField(default='', max_length=32)),
                ('secretary_major', models.CharField(default='', max_length=32)),
                ('secretary_site', models.CharField(default='', max_length=64)),
                ('secretary_picture', models.ImageField(upload_to='eboard/profiles/')),
            ],
            options={
                'db_table': 'eboard',
            },
        ),
    ]
