# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eboard',
            old_name='tresurer_grade',
            new_name='treasurer_grade',
        ),
        migrations.RenameField(
            model_name='eboard',
            old_name='tresurer_major',
            new_name='treasurer_major',
        ),
        migrations.RenameField(
            model_name='eboard',
            old_name='tresurer_name',
            new_name='treasurer_name',
        ),
        migrations.RenameField(
            model_name='eboard',
            old_name='tresurer_picture',
            new_name='treasurer_picture',
        ),
        migrations.RenameField(
            model_name='eboard',
            old_name='tresurer_site',
            new_name='treasurer_site',
        ),
    ]
