# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160408_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eboard',
            name='president_site',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='eboard',
            name='secretary_site',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='eboard',
            name='treasurer_site',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='eboard',
            name='vp_site',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
