# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160408_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eboard',
            name='president_site',
            field=models.CharField(blank=True, default='', help_text='All sites can be blank', max_length=64),
        ),
    ]
